[package]
name = "osm-num-active-contributors"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.83"
chrono = "0.4.38"
clap = { version = "4.5.4", features = ["derive"] }
csv = "1.3.0"
indicatif = "0.17.8"
osmio = "0.11.0"
rayon = "1.10.0"
